Repository Tiryoh/gha-jobid-action, pull requests merged in 2022-01, with the labels that each got.

#3 Make the query script simpler and more robust
  entrypoint.sh
Labels: Type: Bug, Type: Refactoring

#7 docs: Add special thanks
  README.md
Labels: Type: Documentation

#8 feat: Support workflow more than 30 jobs
  README.md
  action.yml
  entrypoint.sh
Labels: Type: Feature

#6 ci: Add test
  .github/workflows/test.yaml
  .github/workflows/version-tag.yaml
Labels: Type: CI, Type: Testing

#9 release: Release v0.1.0
  CHANGELOG.md
Labels: Type: Maintenance
